"""Tableros de ejemplo para el resolutor de sudoku."""

from solver import Board, EMPTY_CELL

EXAMPLE_BOARD: Board = [
    [5, 3, EMPTY_CELL, EMPTY_CELL, 7, EMPTY_CELL, EMPTY_CELL, EMPTY_CELL, EMPTY_CELL],
    [6, EMPTY_CELL, EMPTY_CELL, 1, 9, 5, EMPTY_CELL, EMPTY_CELL, EMPTY_CELL],
    [EMPTY_CELL, 9, 8, EMPTY_CELL, EMPTY_CELL, EMPTY_CELL, EMPTY_CELL, 6, EMPTY_CELL],
    [8, EMPTY_CELL, EMPTY_CELL, EMPTY_CELL, 6, EMPTY_CELL, EMPTY_CELL, EMPTY_CELL, 3],
    [4, EMPTY_CELL, EMPTY_CELL, 8, EMPTY_CELL, 3, EMPTY_CELL, EMPTY_CELL, 1],
    [7, EMPTY_CELL, EMPTY_CELL, EMPTY_CELL, 2, EMPTY_CELL, EMPTY_CELL, EMPTY_CELL, 6],
    [EMPTY_CELL, 6, EMPTY_CELL, EMPTY_CELL, EMPTY_CELL, EMPTY_CELL, 2, 8, EMPTY_CELL],
    [EMPTY_CELL, EMPTY_CELL, EMPTY_CELL, 4, 1, 9, EMPTY_CELL, EMPTY_CELL, 5],
    [EMPTY_CELL, EMPTY_CELL, EMPTY_CELL, EMPTY_CELL, 8, EMPTY_CELL, EMPTY_CELL, 7, 9],
]